const BINGO_EVENTS = [
  // ── GAMEPLAY EVENTS ──────────────────────────────────────
  { id: 1,  text: 'Board wipe played',        cat: 'gameplay' },
  { id: 2,  text: 'Counterspell cast',         cat: 'gameplay' },
  { id: 3,  text: 'Someone tutors',            cat: 'gameplay' },
  { id: 4,  text: 'Commander removed',          cat: 'gameplay' },
  { id: 5,  text: 'Commander tax hits 6+',      cat: 'gameplay' },
  { id: 6,  text: 'Infinite combo attempted',   cat: 'gameplay' },
  { id: 7,  text: 'Land destruction',           cat: 'gameplay' },
  { id: 8,  text: 'Planeswalker enters play',   cat: 'gameplay' },
  { id: 9,  text: 'Artifact destroyed',         cat: 'gameplay' },
  { id: 10, text: 'Enchantment destroyed',      cat: 'gameplay' },
  { id: 11, text: '5+ cards drawn in a turn',   cat: 'gameplay' },
  { id: 12, text: 'Sol Ring on turn 1',         cat: 'gameplay' },
  { id: 13, text: 'Graveyard recursion',        cat: 'gameplay' },
  { id: 14, text: 'Extra turn taken',           cat: 'gameplay' },
  { id: 15, text: 'Permanent stolen',           cat: 'gameplay' },
  { id: 16, text: 'Spell copied',              cat: 'gameplay' },
  { id: 17, text: 'Chaos effect resolves',      cat: 'gameplay' },
  { id: 18, text: 'Lethal commander damage',     cat: 'gameplay' },
  { id: 19, text: 'Free spell cast',           cat: 'gameplay' },
  { id: 20, text: 'Wheel effect played',        cat: 'gameplay' },
  { id: 21, text: 'Power 10+ creature enters',  cat: 'gameplay' },
  { id: 22, text: 'Stack goes 3+ deep',         cat: 'gameplay' },
  { id: 23, text: 'Treasure tokens created',    cat: 'gameplay' },
  { id: 24, text: 'X spell for 10+',           cat: 'gameplay' },
  { id: 25, text: '10+ tokens on board',        cat: 'gameplay' },
  { id: 26, text: '10+ life gained in a turn',  cat: 'gameplay' },
  { id: 27, text: 'Player eliminated',          cat: 'gameplay' },
  { id: 28, text: 'Card played from exile',     cat: 'gameplay' },
  { id: 29, text: '3+ permanents sacrificed',   cat: 'gameplay' },
  { id: 30, text: 'Equipment on commander',      cat: 'gameplay' },
  { id: 31, text: 'Turn 1 mana dork',          cat: 'gameplay' },
  { id: 32, text: 'Cascade triggers',           cat: 'gameplay' },
  { id: 33, text: 'Cyclonic Rift cast',         cat: 'gameplay' },
  { id: 34, text: 'Monarch claimed',            cat: 'gameplay' },
  { id: 35, text: 'Commander cast 3+ times',    cat: 'gameplay' },

  // ── SOCIAL & TABLE TALK EVENTS ───────────────────────────
  { id: 36, text: '"In response!"',             cat: 'social' },
  { id: 37, text: 'Alliance formed',            cat: 'social' },
  { id: 38, text: 'Alliance broken',            cat: 'social' },
  { id: 39, text: 'Rules debate erupts',        cat: 'social' },
  { id: 40, text: '"Does that resolve?"',       cat: 'social' },
  { id: 41, text: '"How much mana open?"',      cat: 'social' },
  { id: 42, text: '"Why are you attacking me?"', cat: 'social' },
  { id: 43, text: 'Card read aloud',            cat: 'social' },
  { id: 44, text: 'Threat assessment debate',    cat: 'social' },
  { id: 45, text: 'Kingmaker moment',           cat: 'social' },
  { id: 46, text: 'Deal offered',               cat: 'social' },
  { id: 47, text: 'Deal broken',                cat: 'social' },
  { id: 48, text: 'Bluffs having interaction',   cat: 'social' },
  { id: 49, text: '"I\'m not the threat!"',     cat: 'social' },
  { id: 50, text: 'Archenemy declared',          cat: 'social' },
  { id: 51, text: 'Someone scoops early',       cat: 'social' },
  { id: 52, text: 'Table groans at a play',     cat: 'social' },
  { id: 53, text: 'Trigger forgotten',          cat: 'social' },
  { id: 54, text: '"Combat?"',                  cat: 'social' },
  { id: 55, text: 'Graveyard checked',          cat: 'social' },
  { id: 56, text: 'Phone check mid-game',       cat: 'social' },
  { id: 57, text: '"That\'s busted!"',          cat: 'social' },
  { id: 58, text: '"Who has removal?"',         cat: 'social' },
  { id: 59, text: 'Awkward silence',            cat: 'social' },
  { id: 60, text: '"I\'ll allow it"',           cat: 'social' },
  { id: 61, text: 'Salt moment',                cat: 'social' },
  { id: 62, text: 'Previous game story told',   cat: 'social' },
  { id: 63, text: '"Should be banned!"',        cat: 'social' },
  { id: 64, text: 'Dice rolled for effect',     cat: 'social' },
  { id: 65, text: '"On your end step..."',      cat: 'social' },
  { id: 66, text: 'Player gets political',      cat: 'social' },
  { id: 67, text: 'Premature celebration',       cat: 'social' },
  { id: 68, text: 'Topdeck saves a player',     cat: 'social' },
];
